Feature/intitial setup
micro-exam/micro-exam-user-api pull request #1
Opened 2021-08-20 03:29 UTC by avanirpatel6

2021-08-21 23:10 UTC, Neil1213 approved these changes

2021-08-22 13:52 UTC, s-pat requested changes

2021-08-22 13:52 UTC, s-pat commented on pom.xml
> +	<description>Demo project for Spring Boot</description>
Can we remove the <name> and <description> tags here?

2021-08-22 13:52 UTC, s-pat commented on pom.xml
> +
Can you add more depos that we will need? Like jdbc, swagger, ect ect

2021-08-24 23:30 UTC, s-pat requested changes

2021-08-24 23:30 UTC, s-pat commented on pom.xml
>  	<artifactId>demo</artifactId>
Change artifact id please

2021-08-25 00:04 UTC, s-pat approved these changes

2021-08-25 00:54 UTC, merged